_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("totaltext_poly_train_rotate_pos",)
  TEST: ("totaltext_poly_test",)  # or "inversetext_test", "totaltext_poly_test_rotate"

MODEL:
  WEIGHTS: "model_final.pth"  # or the provided pre-trained model

SOLVER:
  IMS_PER_BATCH: 3
  BASE_LR: 5e-5
  LR_BACKBONE: 5e-5
  WARMUP_ITERS: 0
  STEPS: (7000,)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 6000

TEST:
  EVAL_PERIOD: 2000

OUTPUT_DIR: "output/yolo6s_transformer_multi_task/totaltext"